# Generated by Django 4.2.20 on 2025-04-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IgboAlphabet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alphabet", models.CharField(max_length=1, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("sound", models.CharField(max_length=50)),
                (
                    "sound_file",
                    models.FileField(
                        blank=True, null=True, upload_to="alphabet_sounds/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Igbo Alphabet",
                "verbose_name_plural": "Igbo Alphabets",
            },
        ),
    ]
