# Generated by Django 4.2.20 on 2025-04-09 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IgboWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100, unique=True)),
                ("meaning", models.CharField(max_length=200)),
                ("example_sentence", models.TextField(blank=True, null=True)),
                (
                    "sound_file",
                    models.FileField(blank=True, null=True, upload_to="word_sounds/"),
                ),
            ],
            options={
                "verbose_name": "Igbo Word",
                "verbose_name_plural": "Igbo Words",
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english_definition", models.TextField()),
                ("part_of_speech", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="DialectWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dialect",
                    models.CharField(
                        choices=[
                            ("CENTRAL", "Central"),
                            ("NGWA", "Ngwa"),
                            ("NSUKKA", "Nsukka"),
                        ],
                        max_length=20,
                    ),
                ),
                ("spelling", models.CharField(max_length=100)),
                (
                    "audio_pronunciation",
                    models.FileField(blank=True, null=True, upload_to="audio/"),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialect_words",
                        to="vocab.word",
                    ),
                ),
            ],
            options={
                "unique_together": {("word", "dialect")},
            },
        ),
    ]
