# Generated by Django 4.2.20 on 2025-07-06 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0002_igboword_word_dialectword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dialectword",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dialect_words",
                to="vocab.igboword",
            ),
        ),
        migrations.DeleteModel(
            name="Word",
        ),
    ]
