# Generated by Django 4.2.20 on 2025-07-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0003_alter_dialectword_word_delete_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="igboword",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
